index:
  path: /
  controller: App\Controller\TestController::index

test:
  path: /test/{age<\d+>?0}
  controller : App\Controller\TestController::test
  methode:  [GET, POST]
  host: localhost
  schemes: [https, http]
  # api.monsite.com && www.monsite.com && monsite.com
  # api.monsite.com / www.monsite.com / monsite.com
  # {age<\d+>?0}
  # defaults:
  #   age: 0
  # requirements:
  #   age: \d+